# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171110_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='blog_entry',
            new_name='entries',
        ),
    ]
