# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171110_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-pub_date']},
        ),
    ]
