# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 01:25
from __future__ import unicode_literals

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171122_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
